import type { Metadata } from "next";
import { OPEN_SANS, RALEWAY } from "../fonts"

import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={ `${OPEN_SANS.variable} ${RALEWAY.variable} `}>
      <body >{children}</body>
    </html>
  );
}
